namespace Presentation.AgentHub.Models;

/// <summary>Identifies the author or purpose of a conversation message.</summary>
public enum MessageRole
{
    /// <summary>A message authored by the end user.</summary>
    User,

    /// <summary>A message generated by the AI assistant.</summary>
    Assistant,

    /// <summary>A system-level instruction injected before the conversation begins.</summary>
    System,

    /// <summary>The result of a tool invocation, fed back to the assistant.</summary>
    Tool,
}
