using Domain.Common.Config;
using Domain.Common.Config.Infrastructure;
using Domain.Common.Workflow;
using Infrastructure.AI.Generators;
using Infrastructure.AI.StateManagement.Checkpoints;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Text;

namespace Infrastructure.AI.StateManagement;

/// <summary>
/// Decorator that adds markdown generation to any state manager.
/// </summary>
/// <remarks>
/// <para><b>Decorator Pattern:</b></para>
/// Wraps an inner IStateManager and adds markdown file generation alongside
/// the inner manager's persistence mechanism.
///
/// <para><b>Dual-Purpose Storage:</b></para>
/// Both representations are "primary" with different purposes:
/// <list type="bullet">
///   <item><b>Inner (JSON)</b>: Machine efficiency, Agent Framework resume capability</item>
///   <item><b>Markdown</b>: Human consumption, git version control, documentation</item>
/// </list>
///
/// <para><b>File Locations:</b></para>
/// - JSON (inner): {BasePath}/{workflowId}/checkpoints/workflow-state.json
/// - Markdown (decorator): {BasePath}/{workflowId}/inputs/workflow-state.md
///
/// <para><b>Operations:</b></para>
/// - Load: Delegates to inner (JSON)
/// - Save: Saves via inner, then generates markdown
/// - Others: Delegate to inner
/// </remarks>
public class MarkdownCheckpointDecorator : IStateManager
{
    private readonly IStateManager _inner;
    private readonly ILogger<MarkdownCheckpointDecorator> _logger;
    private readonly IStateMarkdownGenerator _markdownGenerator;
    private readonly StateManagementConfig _settings;

    /// <summary>
    /// Initializes a new instance of the MarkdownCheckpointDecorator.
    /// </summary>
    /// <param name="inner">The inner state manager (typically JsonCheckpointStateManager)</param>
    /// <param name="logger">Logger for decorator operations</param>
    /// <param name="markdownGenerator">Generator for markdown output</param>
    /// <param name="appConfig">Application configuration</param>
    public MarkdownCheckpointDecorator(
        IStateManager inner,
        ILogger<MarkdownCheckpointDecorator> logger,
        IStateMarkdownGenerator markdownGenerator,
        IOptionsMonitor<AppConfig> appConfig)
    {
        _inner = inner;
        _logger = logger;
        _markdownGenerator = markdownGenerator;
        _settings = appConfig.CurrentValue.Infrastructure.StateManagement;

        // Ensure base path exists
        if (!Directory.Exists(_settings.BasePath))
            Directory.CreateDirectory(_settings.BasePath);
    }

    public async Task<WorkflowState?> LoadAsync(string workflowId, CancellationToken cancellationToken = default)
    {
        // Load from inner (JSON)
        return await _inner.LoadAsync(workflowId, cancellationToken);
    }

    public async Task SaveAsync(WorkflowState state, CancellationToken cancellationToken = default)
    {
        // First save via inner (JSON)
        await _inner.SaveAsync(state, cancellationToken);

        // Then generate markdown (both are primary)
        await GenerateMarkdownAsync(state, cancellationToken);
    }

    public Task<bool> ExistsAsync(string workflowId, CancellationToken cancellationToken = default)
    {
        // Delegate to inner
        return _inner.ExistsAsync(workflowId, cancellationToken);
    }

    public async Task<WorkflowState> CreateAsync(string workflowId, CancellationToken cancellationToken = default)
    {
        // Create via inner, markdown will be generated by SaveAsync
        var state = await _inner.CreateAsync(workflowId, cancellationToken);
        return state;
    }

    public Task<bool> DeleteAsync(string workflowId, CancellationToken cancellationToken = default)
    {
        // Delete via inner, also clean up markdown file
        var task = _inner.DeleteAsync(workflowId, cancellationToken);

        // Clean up markdown file
        var markdownPath = GetMarkdownFilePath(workflowId);
        if (File.Exists(markdownPath))
        {
            try
            {
                File.Delete(markdownPath);
                _logger.LogDebug("Deleted markdown file for workflow: {WorkflowId}", workflowId);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to delete markdown file for workflow: {WorkflowId}", workflowId);
            }
        }

        return task;
    }

    public Task<NodeState?> GetNodeStateAsync(string workflowId, string nodeId, CancellationToken cancellationToken = default)
        => _inner.GetNodeStateAsync(workflowId, nodeId, cancellationToken);

    public Task UpdateNodeStateAsync(string workflowId, string nodeId, NodeState state, CancellationToken cancellationToken = default)
        => _inner.UpdateNodeStateAsync(workflowId, nodeId, state, cancellationToken);

    public Task<List<NodeState>> GetNodesByTypeAsync(string workflowId, string nodeType, CancellationToken cancellationToken = default)
        => _inner.GetNodesByTypeAsync(workflowId, nodeType, cancellationToken);

    public Task<bool> CanTransitionAsync(string workflowId, string nodeId, string toStatus, CancellationToken cancellationToken = default)
        => _inner.CanTransitionAsync(workflowId, nodeId, toStatus, cancellationToken);

    public Task TransitionAsync(string workflowId, string nodeId, string toStatus, CancellationToken cancellationToken = default)
        => _inner.TransitionAsync(workflowId, nodeId, toStatus, cancellationToken);

    public Task SetMetadataAsync(string workflowId, string nodeId, string key, object value, CancellationToken cancellationToken = default)
        => _inner.SetMetadataAsync(workflowId, nodeId, key, value, cancellationToken);

    public Task<T?> GetMetadataAsync<T>(string workflowId, string nodeId, string key, CancellationToken cancellationToken = default)
        => _inner.GetMetadataAsync<T>(workflowId, nodeId, key, cancellationToken);

    public Task<Dictionary<string, object>> GetAllMetadataAsync(string workflowId, string nodeId, CancellationToken cancellationToken = default)
        => _inner.GetAllMetadataAsync(workflowId, nodeId, cancellationToken);

    public Task<bool> IsNodeCompleteAsync(string workflowId, string nodeId, CancellationToken cancellationToken = default)
        => _inner.IsNodeCompleteAsync(workflowId, nodeId, cancellationToken);

    public Task<List<NodeState>> GetIncompleteNodesAsync(string workflowId, CancellationToken cancellationToken = default)
        => _inner.GetIncompleteNodesAsync(workflowId, cancellationToken);

    public Task<List<NodeState>> GetCompletedNodesAsync(string workflowId, CancellationToken cancellationToken = default)
        => _inner.GetCompletedNodesAsync(workflowId, cancellationToken);

    public Task<NodeState?> GetCurrentNodeAsync(string workflowId, CancellationToken cancellationToken = default)
        => _inner.GetCurrentNodeAsync(workflowId, cancellationToken);

    public Task SetCurrentNodeAsync(string workflowId, string nodeId, CancellationToken cancellationToken = default)
        => _inner.SetCurrentNodeAsync(workflowId, nodeId, cancellationToken);

    public Task SetWorkflowStatusAsync(string workflowId, string status, CancellationToken cancellationToken = default)
        => _inner.SetWorkflowStatusAsync(workflowId, status, cancellationToken);

    public Task<string> GetWorkflowStatusAsync(string workflowId, CancellationToken cancellationToken = default)
        => _inner.GetWorkflowStatusAsync(workflowId, cancellationToken);

    public Task CompleteWorkflowAsync(string workflowId, CancellationToken cancellationToken = default)
        => _inner.CompleteWorkflowAsync(workflowId, cancellationToken);

    private async Task GenerateMarkdownAsync(WorkflowState state, CancellationToken cancellationToken)
    {
        if (!_settings.EnableMarkdownGeneration)
            return;

        var markdownPath = GetMarkdownFilePath(state.WorkflowId);
        var directory = Path.GetDirectoryName(markdownPath);

        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        // Write to temp file first for atomic operation
        var tempFilePath = markdownPath + ".tmp";

        try
        {
            var markdown = _markdownGenerator.Generate(state);
            await File.WriteAllTextAsync(tempFilePath, markdown, Encoding.UTF8, cancellationToken);

            // Atomic replace
            if (File.Exists(markdownPath))
                File.Delete(markdownPath);

            File.Move(tempFilePath, markdownPath);

            _logger.LogDebug("Generated markdown for workflow: {WorkflowId}", state.WorkflowId);
        }
        catch
        {
            // Clean up temp file on failure
            if (File.Exists(tempFilePath))
                File.Delete(tempFilePath);
            throw;
        }
    }

    private string GetMarkdownFilePath(string workflowId)
    {
        ValidatePathSegment(workflowId, nameof(workflowId));
        return Path.Combine(_settings.BasePath, workflowId, "inputs", "workflow-state.md");
    }

    /// <summary>
    /// Validates that a path segment does not contain directory traversal sequences
    /// or invalid path characters that could escape the base path.
    /// </summary>
    private static void ValidatePathSegment(string segment, string paramName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(segment, paramName);

        if (segment.Contains("..") ||
            segment.Contains('/') ||
            segment.Contains('\\') ||
            segment.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0)
        {
            throw new ArgumentException(
                $"Value contains invalid path characters or traversal sequences.", paramName);
        }
    }
}
