using Domain.Common.Enums;
using Infrastructure.APIAccess.Auth.Requirements;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;

namespace Infrastructure.APIAccess.Auth.Providers;

/// <summary>
/// Custom authorization policy provider that dynamically creates policies
/// from permission-encoded policy names generated by <see cref="Attributes.PermissionAuthorizeAttribute"/>.
/// </summary>
/// <remarks>
/// <para>
/// ASP.NET Core's default policy provider only resolves policies registered at startup.
/// Because <see cref="Attributes.PermissionAuthorizeAttribute"/> generates policy names
/// dynamically (e.g., <c>"Permission0-2"</c>), a custom provider is required to parse
/// these names and build policies with the corresponding <see cref="PermissionRequirement"/>s.
/// </para>
/// <para>
/// <strong>Policy Name Format:</strong> <c>"Permission{int}-{int}-..."</c>
/// where each integer maps to an <see cref="AuthPermissions"/> enum value.
/// </para>
/// <para>
/// <strong>Registration:</strong>
/// <code>
/// services.AddSingleton&lt;IAuthorizationPolicyProvider, PermissionPolicyProvider&gt;();
/// </code>
/// </para>
/// <para>
/// <strong>Important:</strong> This provider falls back to the default provider for
/// any policy name that does not start with the <c>"Permission"</c> prefix, preserving
/// compatibility with standard <c>[Authorize(Policy = "...")]</c> attributes.
/// </para>
/// </remarks>
public class PermissionPolicyProvider : IAuthorizationPolicyProvider
{
    private const string PolicyPrefix = "Permission";
    private readonly DefaultAuthorizationPolicyProvider _fallbackProvider;

    /// <summary>
    /// Initializes a new instance with a fallback to the default provider.
    /// </summary>
    /// <param name="options">The authorization options used by the default provider.</param>
    public PermissionPolicyProvider(IOptions<AuthorizationOptions> options)
    {
        _fallbackProvider = new DefaultAuthorizationPolicyProvider(options);
    }

    /// <inheritdoc/>
    public Task<AuthorizationPolicy> GetDefaultPolicyAsync()
        => _fallbackProvider.GetDefaultPolicyAsync();

    /// <inheritdoc/>
    public Task<AuthorizationPolicy?> GetFallbackPolicyAsync()
        => _fallbackProvider.GetFallbackPolicyAsync();

    /// <inheritdoc/>
    /// <remarks>
    /// If the policy name starts with <c>"Permission"</c>, parses the suffix as
    /// hyphen-separated integer values, maps each to <see cref="AuthPermissions"/>,
    /// and builds a policy requiring all corresponding <see cref="PermissionRequirement"/>s.
    /// Otherwise, delegates to the default provider.
    /// </remarks>
    public Task<AuthorizationPolicy?> GetPolicyAsync(string policyName)
    {
        if (!policyName.StartsWith(PolicyPrefix, StringComparison.Ordinal))
            return _fallbackProvider.GetPolicyAsync(policyName);

        var permissionSegment = policyName[PolicyPrefix.Length..];

        if (string.IsNullOrEmpty(permissionSegment))
            return _fallbackProvider.GetPolicyAsync(policyName);

        var builder = new AuthorizationPolicyBuilder();

        foreach (var segment in permissionSegment.Split('-', StringSplitOptions.RemoveEmptyEntries))
        {
            if (int.TryParse(segment, out var permissionInt) &&
                Enum.IsDefined(typeof(AuthPermissions), permissionInt))
            {
                builder.AddRequirements(new PermissionRequirement((AuthPermissions)permissionInt));
            }
        }

        builder.RequireAuthenticatedUser();

        return Task.FromResult<AuthorizationPolicy?>(builder.Build());
    }
}
