namespace Application.Common.Models;

/// <summary>
/// Represents a structured audit trail entry recording who performed what action,
/// when, and with what outcome. Generated by <c>AuditTrailBehavior</c> for
/// compliance and traceability of agentic side effects.
/// </summary>
public record AuditEntry
{
    /// <summary>Gets the MediatR request type name.</summary>
    public required string RequestType { get; init; }

    /// <summary>Gets the audit action name (e.g., "FileWrite", "ToolExecution").</summary>
    public required string Action { get; init; }

    /// <summary>Gets the agent that performed the action, if in an agent context.</summary>
    public string? AgentId { get; init; }

    /// <summary>Gets the conversation this action occurred in, if available.</summary>
    public string? ConversationId { get; init; }

    /// <summary>Gets the conversation turn number, if available.</summary>
    public int? TurnNumber { get; init; }

    /// <summary>Gets the UTC timestamp when the action was performed.</summary>
    public required DateTimeOffset Timestamp { get; init; }

    /// <summary>Gets the outcome of the action.</summary>
    public required AuditOutcome Outcome { get; init; }

    /// <summary>Gets the failure reason, if the outcome is not <see cref="AuditOutcome.Success"/>.</summary>
    public string? FailureReason { get; init; }

    /// <summary>Gets optional redacted metadata about the action.</summary>
    public IReadOnlyDictionary<string, string>? Metadata { get; init; }
}

/// <summary>
/// Categorizes the outcome of an audited action.
/// </summary>
public enum AuditOutcome
{
    /// <summary>The action completed successfully.</summary>
    Success,
    /// <summary>The action failed due to an error.</summary>
    Failure,
    /// <summary>The action was denied due to insufficient permissions.</summary>
    Denied
}
