namespace Domain.AI.RAG.Models;

/// <summary>
/// Metadata attached to a <see cref="DocumentChunk"/> that captures provenance,
/// structural context, and optional Anthropic-style contextual enrichment.
/// The contextual prefix is prepended to chunk content before embedding to improve
/// retrieval accuracy by grounding the chunk in its document-level context.
/// </summary>
public record ChunkMetadata
{
    /// <summary>
    /// The URI of the original source document (file path, blob URL, or web URL).
    /// Used for citation generation and deduplication across ingestion runs.
    /// </summary>
    public required Uri SourceUri { get; init; }

    /// <summary>
    /// When this chunk was created during ingestion. Used for freshness-based
    /// ranking and cache invalidation when documents are re-ingested.
    /// </summary>
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// An Anthropic-style contextual prefix generated by an LLM that situates
    /// this chunk within the broader document. Prepended to chunk content before
    /// embedding to improve retrieval precision. Null if contextual enrichment
    /// was not performed or is pending.
    /// </summary>
    public string? ContextualPrefix { get; init; }

    /// <summary>
    /// The chunk ID of the parent section in a hierarchical chunking scheme.
    /// Null for top-level chunks or when using flat chunking strategies.
    /// Enables tree traversal for RAPTOR-style retrieval.
    /// </summary>
    public string? ParentSectionId { get; init; }

    /// <summary>
    /// IDs of chunks that are siblings within the same parent section.
    /// Enables context expansion by retrieving neighboring chunks when
    /// a single chunk provides insufficient context for generation.
    /// </summary>
    public IReadOnlyList<string> SiblingChunkIds { get; init; } = [];

    /// <summary>
    /// The user who ingested the source document, captured from the ambient
    /// knowledge scope at ingestion time. Null when the ingest ran without an
    /// authenticated identity (in-process or CLI callers).
    /// </summary>
    /// <remarks>
    /// This is <strong>provenance, not access control</strong>: retrieval never filters
    /// on it, and the shared-corpus search behavior is unchanged by its presence. It
    /// exists so a future right-to-erasure sweep can find every chunk a given user
    /// contributed — without the stamp there is nothing to sweep by.
    /// </remarks>
    public string? OwnerId { get; init; }

    /// <summary>
    /// The tenant of the caller who ingested the source document, captured from the
    /// ambient knowledge scope at ingestion time. Null when the ingest ran without an
    /// authenticated identity (in-process or CLI callers) or in single-tenant deployments.
    /// </summary>
    /// <remarks>
    /// Like <see cref="OwnerId"/>, this is provenance only. Tenant-level <em>isolation</em>
    /// of the RAG corpus is a separate, opt-in concern
    /// (<c>AppConfig:AI:Rag:ScopedCollections</c>); the stamp is written regardless of
    /// that flag so erasure and audit remain possible for the shared corpus too.
    /// </remarks>
    public string? TenantId { get; init; }
}
