namespace Domain.AI.RAG.Models;

/// <summary>
/// A discrete unit of text extracted from a source document, sized for embedding
/// and retrieval. Each chunk carries its structural position within the document
/// (via <see cref="SectionPath"/>), its metadata for provenance tracking, and
/// optionally its vector embedding once the embedding phase completes.
/// </summary>
public record DocumentChunk
{
    /// <summary>
    /// Unique identifier for this chunk, typically a deterministic hash of
    /// <see cref="DocumentId"/> + offset to ensure idempotent re-ingestion.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Identifier of the source document this chunk was extracted from.
    /// Multiple chunks share the same <see cref="DocumentId"/>, enabling
    /// document-level operations like deletion and re-indexing.
    /// </summary>
    public required string DocumentId { get; init; }

    /// <summary>
    /// A breadcrumb path describing this chunk's position in the document structure.
    /// Format: "TopSection > SubSection > Heading" (e.g., "10-K > Risk Factors > Market Risk").
    /// Built from <see cref="SkeletonNode.GetBreadcrumb"/> during chunking.
    /// </summary>
    public required string SectionPath { get; init; }

    /// <summary>
    /// The raw text content of this chunk. If contextual enrichment was performed,
    /// the <see cref="ChunkMetadata.ContextualPrefix"/> is stored separately in
    /// metadata and prepended only at embedding and retrieval time.
    /// </summary>
    public required string Content { get; init; }

    /// <summary>
    /// The token count of <see cref="Content"/> as measured by the tokenizer
    /// aligned with the embedding model. Used for context budget calculations
    /// and enforcing maximum chunk size constraints.
    /// </summary>
    public required int Tokens { get; init; }

    /// <summary>
    /// Provenance and structural metadata for this chunk, including source URI,
    /// contextual prefix, and sibling/parent relationships.
    /// </summary>
    public required ChunkMetadata Metadata { get; init; }

    /// <summary>
    /// The vector embedding for this chunk's content, generated by the configured
    /// embedding model. Null until the embedding phase of ingestion completes.
    /// The dimensionality depends on the model (e.g., 1536 for text-embedding-ada-002,
    /// 3072 for text-embedding-3-large).
    /// </summary>
    public IReadOnlyList<float>? Embedding { get; init; }
}
